name: "dbt_project"
version: "1.0.0"
config-version: 2

profile: "dbt_project"

vars:
  'dbt_date:time_zone': 'America/Los_Angeles'

analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  +materialized: table
  +post-hook:
    - "{{ dagster.log_columns_in_relation() }}"

query-comment:
  comment: "snowflake_dagster_dbt_v1_opaque_id[[[{{ node.unique_id }}:{{ invocation_id }}]]]"
  append: true